[package]
name = "percy-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = {version = "3.1", features = ["derive"]}
percy-preview-server = {path = "../percy-preview-server"}
tempfile = "3"
tokio = {version = "1", features = ["rt"]}