name: percy-build-test

on: [push]

# TODO: Introduce caching https://github.com/actions/cache/blob/master/examples.md#rust---cargo
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1

    - name: Latest Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          # Used when testing with `wasm-pack test`
          target: wasm32-unknown-unknown

    - name: Rust Version Info
      run: rustc --version && cargo --version && echo $CARGO_HOME

    - name: Install wasm-pack
      run: >
            curl -L https://github.com/rustwasm/wasm-pack/releases/download/v0.9.1/wasm-pack-v0.9.1-x86_64-unknown-linux-musl.tar.gz
            | tar --strip-components=1 --wildcards -xzf - "*/wasm-pack"
            && chmod +x wasm-pack
            && mv wasm-pack $HOME/.cargo/bin/

    - name: Browser versions
      run: wasm-pack --version && firefox --version

    - name: Run all tests
      run: ./test.sh
